[package]
name = "kikoy12345amaba/ovs-demo-web"
version = "0.2.7"
description = "Non Contact Apprehension System demo"

[dependencies]
"wasmer/static-web-server" = "1"

[fs]
"/public" = "dist"
"/settings" = "settings"

[[command]]
name = "run"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/settings/config.toml"]
